@hostname = localhost
@port = 5099
@host = {{hostname}}:{{port}}

### List
GET http://{{host}}/api/game/list 
Content-Type: application/json

### Search Name
GET http://localhost:5099/api/game/search
    ?query=metal

Content-Type: application/json


### By Id
GET http://localhost:5099/api/game/5
Content-Type: application/json